// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  citat: dynamic(() => import("./Citat")),
  home_hero: dynamic(() => import("./HomeHero")),
  newsletter: dynamic(() => import("./Newsletter")),
  rich_text: dynamic(() => import("./RichText")),
};
