// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Clanak documents
 */
interface ClanakDocumentData {
  /**
   * Istaknuta slika field in *Clanak*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: clanak.istaknuta_slika
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  istaknuta_slika: prismic.ImageField<never>;

  /**
   * Naslov field in *Clanak*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: clanak.naslov
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  naslov: prismic.TitleField;

  /**
   * Tekst field in *Clanak*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: clanak.tekst
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tekst: prismic.RichTextField;
}

/**
 * Clanak document from Prismic
 *
 * - **API ID**: `clanak`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ClanakDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ClanakDocumentData>, "clanak", Lang>;

/**
 * Item in *Footer → Linkovi na mreze*
 */
export interface FooterDocumentDataLinkoviNaMrezeItem {
  /**
   * Ikona field in *Footer → Linkovi na mreze*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.linkovi_na_mreze[].ikona
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  ikona: prismic.ImageField<never>;

  /**
   * Link field in *Footer → Linkovi na mreze*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.linkovi_na_mreze[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Footer → Navigacija*
 */
export interface FooterDocumentDataNavigacijaItem {
  /**
   * Link field in *Footer → Navigacija*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.navigacija[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Title field in *Footer → Navigacija*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.navigacija[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Item in *Footer → Dokumenti*
 */
export interface FooterDocumentDataDokumentiItem {
  /**
   * Link field in *Footer → Dokumenti*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.dokumenti[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Title field in *Footer → Dokumenti*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.dokumenti[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Logo field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Adresa field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.adresa
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  adresa: prismic.KeyTextField;

  /**
   * Telefon field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.telefon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  telefon: prismic.KeyTextField;

  /**
   * Email field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Button 1 text field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.button_1_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_1_text: prismic.KeyTextField;

  /**
   * Button 1 link field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.button_1_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_1_link: prismic.LinkField;

  /**
   * Button 2 text field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.button_2_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_2_text: prismic.KeyTextField;

  /**
   * Button 2 link field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.button_2_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_2_link: prismic.LinkField;

  /**
   * Linkovi na mreze field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.linkovi_na_mreze[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  linkovi_na_mreze: prismic.GroupField<
    Simplify<FooterDocumentDataLinkoviNaMrezeItem>
  >;

  /**
   * Navigacija field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.navigacija[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigacija: prismic.GroupField<Simplify<FooterDocumentDataNavigacijaItem>>;

  /**
   * Dokumenti field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.dokumenti[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  dokumenti: prismic.GroupField<Simplify<FooterDocumentDataDokumentiItem>>;

  /**
   * Newsletter title field in *Footer*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.newsletter_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  newsletter_title: prismic.TitleField;

  /**
   * Newsletter button text field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.newsletter_button_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  newsletter_button_text: prismic.KeyTextField;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<FooterDocumentData>, "footer", Lang>;

type HomepageDocumentDataSlicesSlice =
  | NasiLjudiSlice
  | CitatSlice
  | NewsletterSlice
  | HomeHeroSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Title field in *Homepage*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Novosti naslov field in *Homepage*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.novosti_naslov
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  novosti_naslov: prismic.TitleField;

  /**
   * Novosti podnaslov field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.novosti_podnaslov
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  novosti_podnaslov: prismic.RichTextField;

  /**
   * Novosti dugme tekst field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.novosti_dugme_tekst
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  novosti_dugme_tekst: prismic.KeyTextField;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type KoSmoMiDocumentDataSlicesSlice =
  | RichTextSlice
  | ImageHeaderSlice
  | OrganSlice
  | NasiLjudiSlice;

/**
 * Content for Ko smo mi documents
 */
interface KoSmoMiDocumentData {
  /**
   * Slice Zone field in *Ko smo mi*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: ko_smo_mi.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<KoSmoMiDocumentDataSlicesSlice> /**
   * Meta Description field in *Ko smo mi*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: ko_smo_mi.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Ko smo mi*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ko_smo_mi.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Ko smo mi*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: ko_smo_mi.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Ko smo mi document from Prismic
 *
 * - **API ID**: `ko_smo_mi`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type KoSmoMiDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<KoSmoMiDocumentData>,
    "ko_smo_mi",
    Lang
  >;

/**
 * Content for Nasi ljudi documents
 */
interface NasiLjudiDocumentData {
  /**
   * Ime Prezime field in *Nasi ljudi*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: nasi_ljudi.ime_prezime
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  ime_prezime: prismic.TitleField;

  /**
   * Pozicija field in *Nasi ljudi*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nasi_ljudi.pozicija
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  pozicija: prismic.RichTextField;

  /**
   * Slika field in *Nasi ljudi*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nasi_ljudi.slika
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  slika: prismic.ImageField<never>;
}

/**
 * Nasi ljudi document from Prismic
 *
 * - **API ID**: `nasi_ljudi`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NasiLjudiDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<NasiLjudiDocumentData>,
    "nasi_ljudi",
    Lang
  >;

/**
 * Item in *Navbar → Menu 2 submenus*
 */
export interface NavbarDocumentDataMenu2SubmenusItem {
  /**
   * Title field in *Navbar → Menu 2 submenus*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.menu_2_submenus[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Link field in *Navbar → Menu 2 submenus*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.menu_2_submenus[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Navbar → Menu 3 submenus*
 */
export interface NavbarDocumentDataMenu3SubmenusItem {
  /**
   * Title field in *Navbar → Menu 3 submenus*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.menu_3_submenus[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Link field in *Navbar → Menu 3 submenus*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.menu_3_submenus[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Navbar documents
 */
interface NavbarDocumentData {
  /**
   * Logo field in *Navbar*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Button 1 text field in *Navbar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.button_1_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_1_text: prismic.KeyTextField;

  /**
   * Button 1 link field in *Navbar*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.button_1_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_1_link: prismic.LinkField;

  /**
   * Button 2 text field in *Navbar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.button_2_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_2_text: prismic.KeyTextField;

  /**
   * Button 2 link field in *Navbar*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.button_2_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_2_link: prismic.LinkField;

  /**
   * Menu 1 link field in *Navbar*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.menu_1_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  menu_1_link: prismic.LinkField;

  /**
   * Menu 1 text field in *Navbar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.menu_1_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  menu_1_text: prismic.KeyTextField;

  /**
   * Menu 2 text field in *Navbar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.menu_2_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  menu_2_text: prismic.KeyTextField;

  /**
   * Menu 2 submenus field in *Navbar*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.menu_2_submenus[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  menu_2_submenus: prismic.GroupField<
    Simplify<NavbarDocumentDataMenu2SubmenusItem>
  >;

  /**
   * Menu 3 text field in *Navbar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.menu_3_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  menu_3_text: prismic.KeyTextField;

  /**
   * Menu 3 submenus field in *Navbar*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.menu_3_submenus[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  menu_3_submenus: prismic.GroupField<
    Simplify<NavbarDocumentDataMenu3SubmenusItem>
  >;

  /**
   * Menu 4 text field in *Navbar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.menu_4_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  menu_4_text: prismic.KeyTextField;

  /**
   * Menu 4 link field in *Navbar*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.menu_4_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  menu_4_link: prismic.LinkField;

  /**
   * Menu 5 text field in *Navbar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.menu_5_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  menu_5_text: prismic.KeyTextField;

  /**
   * Menu 5 link field in *Navbar*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.menu_5_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  menu_5_link: prismic.LinkField;
}

/**
 * Navbar document from Prismic
 *
 * - **API ID**: `navbar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavbarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<NavbarDocumentData>, "navbar", Lang>;

type PageDocumentDataSlicesSlice = RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type VijestiDocumentDataSlicesSlice = RichTextSlice;

/**
 * Content for Vijesti documents
 */
interface VijestiDocumentData {
  /**
   * Naslov field in *Vijesti*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vijesti.naslov
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  naslov: prismic.RichTextField;

  /**
   * Slice Zone field in *Vijesti*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: vijesti.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<VijestiDocumentDataSlicesSlice> /**
   * Meta Description field in *Vijesti*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: vijesti.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Vijesti*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: vijesti.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Vijesti*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: vijesti.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Vijesti document from Prismic
 *
 * - **API ID**: `vijesti`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type VijestiDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<VijestiDocumentData>,
    "vijesti",
    Lang
  >;

type ZaStaSeZalazemoDocumentDataSlicesSlice = RichTextSlice | ImageHeaderSlice;

/**
 * Content for Za sta se zalazemo documents
 */
interface ZaStaSeZalazemoDocumentData {
  /**
   * Slice Zone field in *Za sta se zalazemo*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: za_sta_se_zalazemo.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ZaStaSeZalazemoDocumentDataSlicesSlice> /**
   * Meta Description field in *Za sta se zalazemo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: za_sta_se_zalazemo.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Za sta se zalazemo*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: za_sta_se_zalazemo.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Za sta se zalazemo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: za_sta_se_zalazemo.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Za sta se zalazemo document from Prismic
 *
 * - **API ID**: `za_sta_se_zalazemo`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ZaStaSeZalazemoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ZaStaSeZalazemoDocumentData>,
    "za_sta_se_zalazemo",
    Lang
  >;

export type AllDocumentTypes =
  | ClanakDocument
  | FooterDocument
  | HomepageDocument
  | KoSmoMiDocument
  | NasiLjudiDocument
  | NavbarDocument
  | PageDocument
  | VijestiDocument
  | ZaStaSeZalazemoDocument;

/**
 * Primary content in *Citat → Primary*
 */
export interface CitatSliceDefaultPrimary {
  /**
   * Citat field in *Citat → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: citat.primary.citat
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  citat: prismic.RichTextField;

  /**
   * Ime Prezime field in *Citat → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: citat.primary.ime_prezime
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  ime_prezime: prismic.RichTextField;

  /**
   * Pozicija field in *Citat → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: citat.primary.pozicija
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  pozicija: prismic.RichTextField;

  /**
   * Slika field in *Citat → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: citat.primary.slika
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  slika: prismic.ImageField<never>;
}

/**
 * Default variation for Citat Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CitatSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CitatSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Citat*
 */
type CitatSliceVariation = CitatSliceDefault;

/**
 * Citat Shared Slice
 *
 * - **API ID**: `citat`
 * - **Description**: Citat
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CitatSlice = prismic.SharedSlice<"citat", CitatSliceVariation>;

/**
 * Primary content in *HomeHero → Primary*
 */
export interface HomeHeroSliceDefaultPrimary {
  /**
   * Hero Image field in *HomeHero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Hero Title field in *HomeHero → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.primary.hero_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  hero_title: prismic.TitleField;

  /**
   * Hero Subtitle field in *HomeHero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.primary.hero_subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  hero_subtitle: prismic.RichTextField;

  /**
   * Primary button text field in *HomeHero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.primary.primary_button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  primary_button_text: prismic.KeyTextField;

  /**
   * Primary button link field in *HomeHero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.primary.primary_button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  primary_button_link: prismic.LinkField;

  /**
   * Secondary button text field in *HomeHero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.primary.secondary_button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  secondary_button_text: prismic.KeyTextField;

  /**
   * Secondary button link field in *HomeHero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.primary.secondary_button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  secondary_button_link: prismic.LinkField;

  /**
   * Hero callout field in *HomeHero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.primary.hero_callout
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  hero_callout: prismic.RichTextField;
}

/**
 * Primary content in *HomeHero → Items*
 */
export interface HomeHeroSliceDefaultItem {
  /**
   * Politike title field in *HomeHero → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.items[].politike_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  politike_title: prismic.RichTextField;

  /**
   * Politike text field in *HomeHero → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.items[].politike_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  politike_text: prismic.RichTextField;

  /**
   * Procitaj vise link field in *HomeHero → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.items[].procitaj_vise_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  procitaj_vise_link: prismic.LinkField;
}

/**
 * Default variation for HomeHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeHeroSliceDefaultPrimary>,
  Simplify<HomeHeroSliceDefaultItem>
>;

/**
 * Slice variation for *HomeHero*
 */
type HomeHeroSliceVariation = HomeHeroSliceDefault;

/**
 * HomeHero Shared Slice
 *
 * - **API ID**: `home_hero`
 * - **Description**: HomeHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeHeroSlice = prismic.SharedSlice<
  "home_hero",
  HomeHeroSliceVariation
>;

/**
 * Primary content in *ImageHeader → Primary*
 */
export interface ImageHeaderSliceDefaultPrimary {
  /**
   * Title field in *ImageHeader → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: image_header.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Background image field in *ImageHeader → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_header.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Default variation for ImageHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageHeader*
 */
type ImageHeaderSliceVariation = ImageHeaderSliceDefault;

/**
 * ImageHeader Shared Slice
 *
 * - **API ID**: `image_header`
 * - **Description**: ImageHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageHeaderSlice = prismic.SharedSlice<
  "image_header",
  ImageHeaderSliceVariation
>;

/**
 * Primary content in *NasiLjudi → Primary*
 */
export interface NasiLjudiSliceDefaultPrimary {
  /**
   * Title field in *NasiLjudi → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: nasi_ljudi.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Subtitle field in *NasiLjudi → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nasi_ljudi.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Button text field in *NasiLjudi → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nasi_ljudi.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;
}

/**
 * Primary content in *NasiLjudi → Items*
 */
export interface NasiLjudiSliceDefaultItem {
  /**
   * Covjek field in *NasiLjudi → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: nasi_ljudi.items[].covjek
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  covjek: prismic.LinkField;
}

/**
 * Default variation for NasiLjudi Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NasiLjudiSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NasiLjudiSliceDefaultPrimary>,
  Simplify<NasiLjudiSliceDefaultItem>
>;

/**
 * Primary content in *NasiLjudi → Primary*
 */
export interface NasiLjudiSlicePagePrimary {
  /**
   * Title field in *NasiLjudi → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: nasi_ljudi.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;
}

/**
 * Primary content in *NasiLjudi → Items*
 */
export interface NasiLjudiSlicePageItem {
  /**
   * Covjek field in *NasiLjudi → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: nasi_ljudi.items[].covjek
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  covjek: prismic.LinkField;
}

/**
 * Page variation for NasiLjudi Slice
 *
 * - **API ID**: `page`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NasiLjudiSlicePage = prismic.SharedSliceVariation<
  "page",
  Simplify<NasiLjudiSlicePagePrimary>,
  Simplify<NasiLjudiSlicePageItem>
>;

/**
 * Slice variation for *NasiLjudi*
 */
type NasiLjudiSliceVariation = NasiLjudiSliceDefault | NasiLjudiSlicePage;

/**
 * NasiLjudi Shared Slice
 *
 * - **API ID**: `nasi_ljudi`
 * - **Description**: NasiLjudi
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NasiLjudiSlice = prismic.SharedSlice<
  "nasi_ljudi",
  NasiLjudiSliceVariation
>;

/**
 * Primary content in *Newsletter → Primary*
 */
export interface NewsletterSliceDefaultPrimary {
  /**
   * Background image field in *Newsletter → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Title field in *Newsletter → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Subtitle field in *Newsletter → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Button text field in *Newsletter → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;
}

/**
 * Default variation for Newsletter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsletterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewsletterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Newsletter*
 */
type NewsletterSliceVariation = NewsletterSliceDefault;

/**
 * Newsletter Shared Slice
 *
 * - **API ID**: `newsletter`
 * - **Description**: Newsletter
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsletterSlice = prismic.SharedSlice<
  "newsletter",
  NewsletterSliceVariation
>;

/**
 * Primary content in *Organ → Primary*
 */
export interface OrganSliceDefaultPrimary {
  /**
   * Naziv organa field in *Organ → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: organ.primary.naziv_organa
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  naziv_organa: prismic.TitleField;
}

/**
 * Primary content in *Organ → Items*
 */
export interface OrganSliceDefaultItem {
  /**
   * Clan field in *Organ → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ime clana
   * - **API ID Path**: organ.items[].clan
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  clan: prismic.RichTextField;

  /**
   * Pozicija field in *Organ → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Pozicija clana
   * - **API ID Path**: organ.items[].pozicija
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  pozicija: prismic.RichTextField;
}

/**
 * Default variation for Organ Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OrganSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OrganSliceDefaultPrimary>,
  Simplify<OrganSliceDefaultItem>
>;

/**
 * Slice variation for *Organ*
 */
type OrganSliceVariation = OrganSliceDefault;

/**
 * Organ Shared Slice
 *
 * - **API ID**: `organ`
 * - **Description**: Organ
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OrganSlice = prismic.SharedSlice<"organ", OrganSliceVariation>;

/**
 * Primary content in *RichText → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *RichText → Primary*
 */
export interface RichTextSliceWithFloatingBoxPrimary {
  /**
   * Content field in *RichText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Floating box title field in *RichText → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.primary.floating_box_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  floating_box_title: prismic.TitleField;
}

/**
 * Primary content in *RichText → Items*
 */
export interface RichTextSliceWithFloatingBoxItem {
  /**
   * Name field in *RichText → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.items[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Link field in *RichText → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * With floating box variation for RichText Slice
 *
 * - **API ID**: `withFloatingBox`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceWithFloatingBox = prismic.SharedSliceVariation<
  "withFloatingBox",
  Simplify<RichTextSliceWithFloatingBoxPrimary>,
  Simplify<RichTextSliceWithFloatingBoxItem>
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation =
  | RichTextSliceDefault
  | RichTextSliceWithFloatingBox;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ClanakDocument,
      ClanakDocumentData,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataLinkoviNaMrezeItem,
      FooterDocumentDataNavigacijaItem,
      FooterDocumentDataDokumentiItem,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      KoSmoMiDocument,
      KoSmoMiDocumentData,
      KoSmoMiDocumentDataSlicesSlice,
      NasiLjudiDocument,
      NasiLjudiDocumentData,
      NavbarDocument,
      NavbarDocumentData,
      NavbarDocumentDataMenu2SubmenusItem,
      NavbarDocumentDataMenu3SubmenusItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      VijestiDocument,
      VijestiDocumentData,
      VijestiDocumentDataSlicesSlice,
      ZaStaSeZalazemoDocument,
      ZaStaSeZalazemoDocumentData,
      ZaStaSeZalazemoDocumentDataSlicesSlice,
      AllDocumentTypes,
      CitatSlice,
      CitatSliceDefaultPrimary,
      CitatSliceVariation,
      CitatSliceDefault,
      HomeHeroSlice,
      HomeHeroSliceDefaultPrimary,
      HomeHeroSliceDefaultItem,
      HomeHeroSliceVariation,
      HomeHeroSliceDefault,
      ImageHeaderSlice,
      ImageHeaderSliceDefaultPrimary,
      ImageHeaderSliceVariation,
      ImageHeaderSliceDefault,
      NasiLjudiSlice,
      NasiLjudiSliceDefaultPrimary,
      NasiLjudiSliceDefaultItem,
      NasiLjudiSlicePagePrimary,
      NasiLjudiSlicePageItem,
      NasiLjudiSliceVariation,
      NasiLjudiSliceDefault,
      NasiLjudiSlicePage,
      NewsletterSlice,
      NewsletterSliceDefaultPrimary,
      NewsletterSliceVariation,
      NewsletterSliceDefault,
      OrganSlice,
      OrganSliceDefaultPrimary,
      OrganSliceDefaultItem,
      OrganSliceVariation,
      OrganSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceWithFloatingBoxPrimary,
      RichTextSliceWithFloatingBoxItem,
      RichTextSliceVariation,
      RichTextSliceDefault,
      RichTextSliceWithFloatingBox,
    };
  }
}
